services:

  mariadb:
    build:
      context: requirements/mariadb
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    volumes:
      - $HOME/data/db:/var/lib/mysql
    secrets:
      - initfile.sql

  nginx:
    build:
      context: requirements/nginx
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    depends_on:
      - wordpress

  wordpress:
    build:
      context: requirements/wordpress
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    depends_on:
      mariadb:
        condition: service_healthy

secrets:
  initfile.sql:
    file: ../secrets/initfile.sql
