x-build-args: &build_args
  args:
    ALPINE_VERSION: ${ALPINE_VERSION}

services:

  mariadb:
    build:
      context: requirements/mariadb
      <<: *build_args
    volumes:
      - $HOME/data/db:/var/lib/mysql
    secrets:
      - initfile.sql

  nginx:
    build:
      context: requirements/nginx
      <<: *build_args
    volumes:
      - $HOME/data/wordpress:/var/www
    ports:
      - ${HTTPS_PORT}:443
    secrets:
      - cert.key
      - cert.pem
    depends_on:
      wordpress:
        condition: service_healthy

  wordpress:
    build:
      context: requirements/wordpress
      <<: *build_args
    volumes:
      - $HOME/data/wordpress:/var/www
    environment:
      - DOMAIN_NAME
      - WORDPRESS_TITLE
    secrets:
      - password_db_wordpress.txt
      - password_wordpress_deydoux.txt
      - password_wordpress_root.txt
    depends_on:
      mariadb:
        condition: service_healthy

secrets:
  cert.key:
    file: ${SECRETS_DIR}/cert.key
  cert.pem:
    file: ${SECRETS_DIR}/cert.pem
  initfile.sql:
    file: ${SECRETS_DIR}/initfile.sql
  password_db_wordpress.txt:
    file: ${SECRETS_DIR}/password_db_wordpress.txt
  password_wordpress_deydoux.txt:
    file: ${SECRETS_DIR}/password_wordpress_deydoux.txt
  password_wordpress_root.txt:
    file: ${SECRETS_DIR}/password_wordpress_root.txt

