x-build-args: &build_args
  args:
    ALPINE_VERSION: ${ALPINE_VERSION}

services:

  adminer:
    build:
      context: requirements/bonus/adminer
      <<: *build_args
    volumes:
      - adminer:/var/www/adminer
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    build:
      context: requirements/mariadb
      <<: *build_args
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    secrets:
      - initfile.sql

  nginx:
    build:
      context: requirements/nginx
      <<: *build_args
    volumes:
      - adminer:/var/www/adminer:ro
      - wordpress:/var/www/wordpress:ro
    networks:
      - inception
    ports:
      - "443:443"
    secrets:
      - cert.key
      - cert.pem
    depends_on:
      adminer:
        condition: service_healthy
      wordpress:
        condition: service_healthy

  proftpd:
    build:
      context: requirements/bonus/proftpd
      <<: *build_args
    volumes:
      - wordpress:/var/lib/ftp
    networks:
      - inception
    ports:
      - "21:21"
    secrets:
      - password_proftpd_root.txt

  redis:
    build:
      context: requirements/bonus/redis
      <<: *build_args
    networks:
      - inception
    secrets:
      - password_redis.txt
      - redis.conf

  wordpress:
    build:
      context: requirements/wordpress
      <<: *build_args
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    environment:
      - DOMAIN_NAME
      - WORDPRESS_TITLE
    secrets:
      - password_db_wordpress.txt
      - password_redis.txt
      - password_wordpress_deydoux.txt
      - password_wordpress_root.txt
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:

  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/db

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress

  adminer:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/adminer

networks:
  inception:
    driver: bridge

secrets:
  cert.key:
    file: ${SECRETS_DIR}/cert.key
  cert.pem:
    file: ${SECRETS_DIR}/cert.pem
  initfile.sql:
    file: ${SECRETS_DIR}/initfile.sql
  password_db_wordpress.txt:
    file: ${SECRETS_DIR}/password_db_wordpress.txt
  password_proftpd_root.txt:
    file: ${SECRETS_DIR}/password_proftpd_root.txt
  password_redis.txt:
    file: ${SECRETS_DIR}/password_redis.txt
  password_wordpress_deydoux.txt:
    file: ${SECRETS_DIR}/password_wordpress_deydoux.txt
  password_wordpress_root.txt:
    file: ${SECRETS_DIR}/password_wordpress_root.txt
  redis.conf:
    file: ${SECRETS_DIR}/redis.conf

