x-build-args: &build_args
  args:
    ALPINE_VERSION: ${ALPINE_VERSION}

services:

  mariadb:
    build:
      context: requirements/mariadb
      <<: *build_args
    volumes:
      - $HOME/data/db:/var/lib/mysql
    secrets:
      - initfile.sql

  nginx:
    build:
      context: requirements/nginx
      <<: *build_args
    ports:
      - ${HTTPS_PORT}:443
      - 8080:80
    # depends_on:
    #   - wordpress

  wordpress:
    build:
      context: requirements/wordpress
      <<: *build_args
    depends_on:
      mariadb:
        condition: service_healthy

secrets:
  initfile.sql:
    file: ../secrets/initfile.sql
