services:

  mariadb:
    build: requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    secrets:
      - initfile.sql

  nginx:
    build: requirements/nginx
    volumes:
      - wordpress:/var/www/wordpress:ro
    networks:
      - inception
    ports:
      - "443:443"
    secrets:
      - cert.key
      - cert.pem
    depends_on:
      wordpress:
        condition: service_healthy

  redis:
    build: requirements/redis
    networks:
      - inception
    secrets:
      - password_redis.txt
      - redis.conf

  vsftpd:
    build: requirements/vsftpd
    volumes:
      - wordpress:/var/lib/ftp
    networks:
      - inception
    ports:
      - "21:21"
    secrets:
      - cert.key
      - cert.pem
      - password_vsftpd_root.txt

  wordpress:
    build: requirements/wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    environment:
      - DOMAIN_NAME
      - WORDPRESS_TITLE
    secrets:
      - password_db_wordpress.txt
      - password_redis.txt
      - password_wordpress_deydoux.txt
      - password_wordpress_root.txt
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/db
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress

networks:
  inception:
    driver: bridge

secrets:
  cert.key:
    file: ${SECRETS_DIR}/cert.key
  cert.pem:
    file: ${SECRETS_DIR}/cert.pem
  initfile.sql:
    file: ${SECRETS_DIR}/initfile.sql
  password_db_wordpress.txt:
    file: ${SECRETS_DIR}/password_db_wordpress.txt
  password_redis.txt:
    file: ${SECRETS_DIR}/password_redis.txt
  password_vsftpd_root.txt:
    file: ${SECRETS_DIR}/password_vsftpd_root.txt
  password_wordpress_deydoux.txt:
    file: ${SECRETS_DIR}/password_wordpress_deydoux.txt
  password_wordpress_root.txt:
    file: ${SECRETS_DIR}/password_wordpress_root.txt
  redis.conf:
    file: ${SECRETS_DIR}/redis.conf

